SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_SPEED = 9
TILE_SIZE = 40
JUMP_SPEED = 20
MAX_FALL_SPEED = 20
MAX_JUMP_TIMER = 20
COYOTE_JUMP_TIME = 7
DASH_TIMER = 10
DASH_COOLDOWN = 40
DASH_SPEED = 2*PLAYER_SPEED



PORTES_CORRESPONDANCES = {
    "1-1-TODO" : "machin"
}
